### PR TITLE
Update to V11 style data (Deprecated)

### LINKED ISSUE #186: [BUG] The module "token-mold" contains "dependencies" which is deprecated in favor of "relationships.requires"
**Describe the bug**
Curent version (as of today) of FoundryVTT and DnD5e game system (2.3.1) with token mold add-in.

**To Reproduce**
have all 3 above and you'll see this error.  We are using this with game world "odyssey of the dragonlords" if that helps.

**Expected behavior**
no error and the token-mold features work.

**Module incompatibilities**
none that we can see

**Desktop (please complete the following information):**
 - OS: Windows 10 22h2
 - Browser Edge Chromium (Current)
 - FVTT Version 11.308
 - Module version 2.20.3

### LINKED ISSUE #197: [BUG] configure dialog doesn't open for D&D 5e
**Describe the bug**
I am running the most updated version of foundry and the Dungeons and Dragons 5e system. When I try to update token mold's token configure options, the dialog doesn't pop up. This is the error from the console:

foundry.js:753  TypeError: An error occurred while rendering TokenMoldForm 41. Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at get _actorAttributes [as _actorAttributes] (token-mold.js:1324:32)
    at TokenMoldForm.getData (token-mold.js:1081:33)
    at TokenMoldForm._render (foundry.js:5812:29)
    at TokenMoldForm._render (foundry.js:6532:17)
    at TokenMoldForm.render (foundry.js:5769:10)
    at HTMLAnchorElement.<anonymous> (token-mold.js:268:19)

**To Reproduce**
1. Create a world with the D&D 5e system 
2. go to actors tab
3. open development console
4. click on the settings icon for token mold
image
5. See error (only on console, nothing happens in UX at all)

**Expected behavior**
The dialog with the token configuration settings should pop up and let me update the settings

**Module incompatibilities**
I have no other modules active (and have not turned any on since I created a new world to test this)

**Desktop (please complete the following information):**
 - OS: My laptop is running windows 11, the VM running foundry is on Ubuntu
 - Browser: Edge
 - FVTT Version:  11 build 3.15
 - System version: 3.0.1
 - Module version: 2.20.3

### LINKED ISSUE #202: [BUG] Gear wheel is not bringing up Token Mold Icons
Hi there thanks so much for taking the time to help.
I wanted to change some of the settings in Token Mold and I have attempted to access the settings through the gear wheel on the Actors tab: 
image

Whenever I click on it nothing happens. No pop up, no message, nothing. I recently started using this mod and I wanted to create custom names for my enemy actors. It seems to work fine in the background with the prepended descriptors appearing when I drag enemies onto the scene. 

**Describe the bug**
Here are the  console errors (F12 for most browsers) that occur.
image

**To Reproduce**
1. Go to 'Actor's Panell'
2. Click on 'Gear Wheel'
3. Nothing Appears
4. No Error

**Expected behavior**
Open the settings for token mold.

**Module incompatibilities**
Please try to reproduce your bug with all other modules deactivated. If this module clashes with another module, please find that module and report it here.  
The [find the culprit](https://github.com/Moerill/fvtt-find-the-culprit/) module may prove to be useful here.

**Screenshots/GIFs/Videos**

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - FVTT - Forge V11 stable Patch 13 build 315
 

**Additional context**

### PR DESCRIPTION
**Pull request by BeardedGnome**
EDIT:
See here: https://github.com/Moerill/token-mold/pull/205

This PR pulls from my master branch which now has changes to allow me to publish from my fork. The linked PR is from the commit before those changes were added and is suitable to merge to Moerill:master.

Original:

ESLint/Prettier made a lot of extraneous changes. The important ones are:
* Remove V9 and V10 support
* Change actorAttributes to use new V11 system data model as described here: https://foundryvtt.com/article/active-effects/

fixes #202 
fixes #197 
fixes #186

### CODE REVIEW

**Comment by BeardedGnome** [comment]
@Moerill and @Geekswordsman ,

I apologize for the mess ESLint/Prettier made of your code. Hopefully the v11 fix I made in `_actorAttributes()` is clear.

**Comment by BeardedGnome** [comment]
@paladintodd and @JasonSunday ,

Can you see if this change fixes Savage Worlds for you?

**Comment by JasonSunday** [comment]
It is still the same. 
token-mold

**Comment by BeardedGnome** [comment]
Strange. It's working for me. Are you using the version from this PR or using Moerill's release?

image

**Comment by JasonSunday** [comment]
Moerill's release.

**Comment by BeardedGnome** [comment]
I've never tried installing it from GithHub, but you can try this URL:
https://[raw.githubusercontent.com/BeardedGnome/token-mold/master/module.json](https://raw.githubusercontent.com/BeardedGnome/token-mold/master/module.json)

**Comment by Visovsiouk** [comment]
Hello, @BeardedGnome, I tried using your module from the manifest provided, but there seems to be an error. In your `manifest.json` you include a release that does not exist.

```
"download": "https://github.com/Moerill/token-mold/releases/download/v2.21.0/v2.21.0.zip",
```

You should create a release from a tag in your fork and replace this inclusion with your own something like.

```
"download": "https://github.com/BeardedGnome/token-mold/releases/download/v2.21.0/v2.21.0.zip",
```

**Comment by BeardedGnome** [comment]
@Visovsiouk
@JasonSunday 

Figured out how to publish a release. Unfortunately, it broke this PR. I'll have to figure out how to fix that now.

**Comment by BeardedGnome** [comment]
@Visovsiouk 
@JasonSunday 

Does it work for you?
`https://raw.githubusercontent.com/BeardedGnome/token-mold/master/module.json`

**Comment by BeardedGnome** [comment]
I had to publish a breaking version for Foundry v12:

Foundry v11:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.21.0/module.json`
Foundry v12:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

**Pull request closed without merging**
