### PR TITLE
fixing some null reference exceptions

### PR DESCRIPTION
**Pull request by ryzimmer**
Fixing some null reference issues that seem to be breaking the config dialog for dnd 5e

### CODE REVIEW

**Comment by orozcojoejr** [comment]
When I try to download the code and install on foundry I am still getting the issue. Is there a manifest url for this specific pull?

**Comment by ryzimmer** [comment]
No there isn’t, but it’s a pretty easy change to emulate the fix for, you can put breakpoints and run the if statements and if they’re true assign the value to an empty array, (you can do this for the first line also where I used || []). Basically the issue is just that there are a bunch of values that used to be set and seem to be null in the new version. This is meant as a quick fix, but you’re welcome to create an actual fix for the issue if you want.

Ryan

On Feb 11, 2024, at 10:12 AM, orozcojoejr ***@***.***> wrote:

﻿

When I try to download the code and install on foundry I am still getting the issue. Is there a manifest url for this specific pull?

**Comment by ryzimmer** [comment]
You could also just add a manifest change if you want to test it. I gave approvers permissions to make changes to the PR themselves.

Ryan

On Feb 11, 2024, at 12:17 PM, Ryan Zimmerman ***@***.***> wrote:

﻿
No there isn’t, but it’s a pretty easy change to emulate the fix for, you can put breakpoints and run the if statements and if they’re true assign the value to an empty array, (you can do this for the first line also where I used || []). Basically the issue is just that there are a bunch of values that used to be set and seem to be null in the new version. This is meant as a quick fix, but you’re welcome to create an actual fix for the issue if you want.

Ryan

On Feb 11, 2024, at 10:12 AM, orozcojoejr ***@***.***> wrote:

﻿

When I try to download the code and install on foundry I am still getting the issue. Is there a manifest url for this specific pull?

**Review by Joe-Engineer — APPROVED** [review]

**Comment by KomradeKoshka85** [comment]
I was looking at the console for the error and added the fixes that @Joe-Engineer approved of 15 hours ago and still wasn't able to get the settings screen to pop up, i decided to comment out lines 1317 - 1344 and I did manage to get the settings menu to open, not the most elegant fix but hey, no null pointer exceptions if theres nothing to call on the null pointer exception LOL

**Comment by thedmmatt** [comment]
Actually, the issue persists. I managed to get it working perfectly (and opening the config dialog) by changing line 1081 of the tokenMold.js file from "data.actorAttributes = this._actorAttributes;" to "data.actorAttributes = this.actorAttributes;".

Yes, a single underscore was (so far) the culprit; I guess it has something to do with how v11 (or maybe D&D 5e v3, since I haven't tested other systems) handles actorAttributes.

**Comment by ryzimmer** [comment]
Cool for anyone this is blocking and can’t wait, if you just throw breakpoints in the js you can manually set the values that are null referencing to [] and it will open (it’s the 3 that my original change was setting)

On Feb 25, 2024, at 12:47 PM, Matt Dutra ***@***.***> wrote:

﻿

Actually, the issue persists. I managed to get it working perfectly (and opening the config dialog) by changing line 1081 of the tokenMold.js file from "data.actorAttributes = this._actorAttributes;" to "data.actorAttributes = this.actorAttributes;".

Yes, a single underscore was (so far) the culprit; I guess it has something to do with how v11 (or maybe D&D 5e v3, since I haven't tested other systems) handles actorAttributes.

**Comment by sseritan** [comment]
Just +1'ing @thedmmatt's solution, worked perfectly for me on Foundry 11.315, 5e version 3.0.3 on Mac OS Chrome.

**Comment by kmorey** [comment]
Also +1'ing @thedmmatt's solution which also worked for me to get the dialog to finally open by modifying the JS with dev tools. Foundry 11.315, 5e 3.1.2 on Mac OS Chrome.

Would be nice to get this merged and into the next release in case my DM needs to make more token changes :)

**Comment by BeardedGnome** [comment]
I don't think this is required anymore. If you disagree, let me know.

**Pull request closed without merging**
